server:
    port: 8081
spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: CITIZEN-SVC
          uri: http://localhost:8083
            #lb: //CITIZEN-SVC
          predicates:
            - Path=/citizen/**


        - id: VACCINATION-CENTER
          uri: http://localhost:8084
          predicates:
           - Path=/vaccination/**


